// This file is autogenerated. Changes will be overwritten.
#include "WSCMZZOQ67/moc_BoardModel.cpp"
#include "WSCMZZOQ67/moc_ChessController.cpp"
#include "WSCMZZOQ67/moc_GameClock.cpp"
#include "WSCMZZOQ67/moc_GameLogger.cpp"
#include "WSCMZZOQ67/moc_MatchManager.cpp"
